services:
  - type: web
    name: vertexsol-backend
    runtime: docker
    region: frankfurt # or singapore/us
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    buildCommand: npm install && npm run build
    startCommand: npm start

  - type: web
    name: vertexsol-frontend
    env: docker
    region: frankfurt
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://vertexsol-backend.onrender.com

databases:
  - name: vertexsol-db
    region: frankfurt
    plan: free
    databaseName: vertexsol_prod
    ipAllowList:
      - group: render-web-services
